site_name: 钱学森班学习指南
site_description: 钱学森班课程与学习指引站点
site_author: 钱学组
repo_name: XJTU-QXZ/QXSCourses    
repo_url: https://github.com/XJTU-Qian-Xuesen-Class/XJTU-QXZ  # 仓库地址
site_url: https://xjtu-qian-xuesen-class.github.io/XJTU-QXZ/  # 替换为你的实际 URL
docs_dir: docs
theme:
  custom_dir: overrides
  name: material
  icon:
    logo: material/library
  language: zh
  encoding: utf-8
 
  palette:
    # Light mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: 夜间模式
    # Dark mode
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: 白天模式

  features:
    - header.repo
    - navigation.tabs #多个分类标签
    - navigation.top #顶部导航
    - search.highlight #搜索高亮
    - navigation.expand #展开导航
    - navigation.sections #导航分组
    - navigation.instant #即时导航
    - search.suggest #搜索建议
    - layout.footer #页脚
    - navigation.footer
    - toc.follow #目录跟随
    - navigation.tracking #导航追随
    - content.code.copy #代码复制

nav:
  - 主页:
    - 主页: 主页/index.md
    - 贡献指南: 主页/contribution_guide.md
    - 课程页面模板: 主页/course_template.md
    - 更新历史:  
      - 说明: 主页/update_history.md
      - 更新日志: changelog.md
  
  - 思政:
    - 思政: 思政/index.md
    - 思想道德与法治: 思政/思想道德与法治311.md
    - 中国近现代史纲要: 思政/中国近现代史纲要212.md
    - 毛泽东思想和中国特色社会主义理论体系概论: 思政/毛泽东思想和中国特色社会主义理论体系概论221.md
    - 马克思主义基本原理: 思政/马克思主义基本原理322.md
    - 习近平新时代中国特色社会主义思想概论: 思政/习近平新时代中国特色社会主义思想概论322.md
    - 国防教育: 思政/国防教育212.md
    - 形势与政策: 思政/形势与政策2.md
  
  - 体育:
    - 体育: 体育/index.md
    - 羽毛球: 体育/羽毛球.md
    - 足球1: 体育/足球1.md
    - 极限飞盘: 体育/极限飞盘.md
    - 体适能: 体育/体适能.md
    - 匹克球: 体育/匹克球.md
    - 跳绳: 体育/跳绳.md



  - 通识教育课:
    - 通识教育课: 通识教育课/index.md
    - 艺术类课程:
      - 艺术欣赏与创作陶艺: 通识教育课/艺术类课程/艺术欣赏与创作陶艺111.md
      - 艺术欣赏与创作音乐: 通识教育课/艺术类课程/艺术欣赏与创作音乐111.md
      - 艺术欣赏与创作书法: 通识教育课/艺术类课程/艺术欣赏与创作书法111.md
      - 艺术与科学的交汇: 通识教育课/艺术类课程/艺术与科学的交汇122.md
    - 社科类课程:
      - 经济学概论: 通识教育课/社科类课程/经济学概论222.md
      - 管理学基础: 通识教育课/社科类课程/管理学基础222.md
      - 社会学的视野: 通识教育课/社科类课程/社会学的视野221.md
      - 创新思维培养与实践: 通识教育课/社科类课程/创新思维培养与实践221.md
    - 系统科学课:
      - 重大工程设计导论: 通识教育课/系统科学课/重大工程设计导论132.md
      - 系统工程: 通识教育课/系统科学课/系统工程222.md
    - 公共课程类:
      - 学术英语素养: 通识教育课/公共课程类/学术英语素养211.md
      - 国际交流演讲与辩论: 通识教育课/公共课程类/国际交流演讲与辩论212.md
      - 托福强化: 通识教育课/公共课程类/托福强化212.md
      - 英语学术写作与展示: 通识教育课/公共课程类/英语学术写作与展示212.md
      - 日语基础: 通识教育课/公共课程类/日语基础212.md
      - 综合工程训练1: 通识教育课/公共课程类/综合工程训练1 1 1-1.md
      - 综合工程训练2: 通识教育课/公共课程类/综合工程训练2 1 1-2.md
    - 校选通识课:
      - 国际关系分析: 通识教育课/校选通识课/国际关系分析.md
      - 跨文化学术交流基础: 通识教育课/校选通识课/跨文化学术交流基础.md
      - 全球气候史: 通识教育课/校选通识课/全球气候史.md
      - 走进天文学: 通识教育课/校选通识课/走进天文学.md
      - 新能源导论: 通识教育课/校选通识课/新能源导论.md
      - 健康与疾病: 通识教育课/校选通识课/健康与疾病.md

  - 数理基础课: 
    - 数理基础课: 数理基础课/index.md
    - 工科数学分析-1: 数理基础课/工科数学分析-1 6 1-1.md
    - 工科数学分析-2: 数理基础课/工科数学分析-2 6 1-2.md
    - 线性代数与解析几何I: 数理基础课/线性代数与解析几何I 4 1-1.md
    - 化学原理: 数理基础课/化学原理 5 1-1.md
    - 复变函数与积分变换: 数理基础课/复变函数与积分变换 3 2-1.md
    - 数学物理方程: 数理基础课/数学物理方程 2 2-1.md
    - 概率统计与随机过程: 数理基础课/概率统计与随机过程 4 2-2.md
    - 数值分析: 数理基础课/数值分析 3 2-2.md
    - 大学物理学（理论）1: 数理基础课/大学物理学（理论）1 4 1-2.md
    - 大学物理学（理论）2: 数理基础课/大学物理学（理论）2 4 2-1.md
    - 大学物理学（理论）3: 数理基础课/大学物理学（理论）3 2 2-1.md
    - 大学物理学（实验）Ⅰ: 数理基础课/大学物理学（实验）Ⅰ 1 1-2.md
    - 大学物理学（实验）Ⅱ: 数理基础课/大学物理学（实验）Ⅱ 1 2-1.md
  
  - 技术基础课:
    - 技术基础课: 技术基础课/index.md
    - 人工智能导论: 技术基础课/人工智能导论 2 3-2.md
    - 自动控制原理: 技术基础课/自动控制原理 4 3-1.md
    - 程序设计思想方法与实践: 技术基础课/程序设计思想方法与实践 3 1-2.md
    - 电子技术基础: 技术基础课/电子技术基础 5 2-2.md
    - 电路: 技术基础课/电路 4 2-1.md
    - 工程图学: 技术基础课/工程图学 3 1-1.md
    - 理论力学II: 技术基础课/理论力学II 4 2-1.md

  - 主攻专业课:
    - 主攻专业课: 主攻专业课/index.md
    - 自动化专业课程:
      - 数字信号处理: 主攻专业课/自动化专业课程/数字信号处理 3 3-1.md
      - 运筹学I: 主攻专业课/自动化专业课程/运筹学I 3 2-2.md
      - 计算机原理与嵌入式系统设计（钱）: 主攻专业课/自动化专业课程/计算机原理与嵌入式系统设计（钱） 4 3-1.md
      - 数据结构与算法II: 主攻专业课/自动化专业课程/数据结构与算法II 3 3-1.md
      - 智能车控制项目设计（钱）: 主攻专业课/自动化专业课程/智能车控制项目设计（钱） 1 4-1.md
      - 离散数学Ⅱ: 主攻专业课/自动化专业课程/离散数学Ⅱ 3 3-1.md
      - 人工智能的现代方法II-机器学习: 主攻专业课/自动化专业课程/人工智能的现代方法II-机器学习 2.5 3-2.md
      - 机器人学基础（钱）: 主攻专业课/自动化专业课程/机器人学基础（钱） 3 4-1.md
      - 运动控制系统（钱）: 主攻专业课/自动化专业课程/运动控制系统（钱） 2.5 3-2.md
      - 检测技术基础与计算机视觉: 主攻专业课/自动化专业课程/检测技术基础与计算机视觉 4 4-1.md
      - 计算机网络原理与应用: 主攻专业课/自动化专业课程/计算机网络原理与应用 2.5 3-2.md
    - 电气工程专业课程:
      - 电磁场与波: 主攻专业课/电气工程专业课程/电磁场与波 4 2-2.md
      - 信号与系统II: 主攻专业课/电气工程专业课程/信号与系统II 3.5 2-2.md
      - 电机学: 主攻专业课/电气工程专业课程/电机学 4.5 3-1.md
      - 基于PBL（Project-Based Learning）的科研训练: 主攻专业课/电气工程专业课程/基于PBL（Project-Based Learning）的科研训练 8 4-2.md
      - 电力设备设计原理: 主攻专业课/电气工程专业课程/电力设备设计原理 2 3-1.md
      - 电气材料基础: 主攻专业课/电气工程专业课程/电气材料基础 2 3-1.md
      - 电力系统稳态分析: 主攻专业课/电气工程专业课程/电力系统稳态分析 4 3-1.md
      - 大数据科学与应用技术: 主攻专业课/电气工程专业课程/大数据科学与应用技术 2 3-2.md
      - 电力电子技术（英）: 主攻专业课/电气工程专业课程/电力电子技术（英） 3.5 3-2.md
      - 高压电技术: 主攻专业课/电气工程专业课程/高压电技术 3 3-2.md
    - 能源与动力工程专业课程:
      - 流体力学（英）: 主攻专业课/能源与动力工程专业课程/流体力学（英） 3.5 2-2.md
      - 工程热力学（英）: 主攻专业课/能源与动力工程专业课程/工程热力学（英） 3.5 2-2.md
      - 热流体课程实验-1: 主攻专业课/能源与动力工程专业课程/热流体课程实验-1 1 2-2.md
      - 传热学（英）: 主攻专业课/能源与动力工程专业课程/传热学（英） 3.5 3-1.md
      - 燃烧学I: 主攻专业课/能源与动力工程专业课程/燃烧学I 2.5 3-1.md
      - 工程材料基础: 主攻专业课/能源与动力工程专业课程/工程材料基础 3 3-1.md
      - 热流体课程实验-2: 主攻专业课/能源与动力工程专业课程/热流体课程实验-2 0.5 3-1.md
      - 热流问题数值计算: 主攻专业课/能源与动力工程专业课程/热流问题数值计算 2 4-1.md
      - 现代电力生产技术: 主攻专业课/能源与动力工程专业课程/现代电力生产技术 3 3-2.md
      - 储能原理与应用: 主攻专业课/能源与动力工程专业课程/储能原理与应用 3 3-2.md
      - 先进制冷低温技术: 主攻专业课/能源与动力工程专业课程/先进制冷低温技术 3 3-2.md
    - 智能制造专业课程:
      - 运动控制系统（钱）: 主攻专业课/智能制造专业课程/运动控制系统（钱） 2.5 3-2.md
      - 热工基础Ⅰ: 主攻专业课/智能制造专业课程/热工基础Ⅰ 2.5 2-2.md
      - 工程材料及成形技术基础: 主攻专业课/智能制造专业课程/工程材料及成形技术基础 3 3-1.md
      - 大数据技术: 主攻专业课/智能制造专业课程/大数据技术 2 3-2.md
      - 智能检测技术基础: 主攻专业课/智能制造专业课程/智能检测技术基础 4 3-1.md
      - 材料力学: 主攻专业课/智能制造专业课程/材料力学 3.5 2-2.md
      - 基础力学实验-2: 主攻专业课/智能制造专业课程/基础力学实验-2 0.5 2-2.md
      - 机器人技术及应用: 主攻专业课/智能制造专业课程/机器人技术及应用 2 3-2.md
      - 机械设计基础: 主攻专业课/智能制造专业课程/机械设计基础 4 3-1.md
      - 车间智能执行系统技术: 主攻专业课/智能制造专业课程/车间智能执行系统技术 2.5 4-1.md
      - 智能制造技术基础: 主攻专业课/智能制造专业课程/智能制造技术基础 3.5 3-2.md
  
  - 辅修专业课:
    - 辅修专业课: 辅修专业课程/index.md
    - 自动化（信息）辅修课程:
      - 通信原理与应用: 辅修专业课程/自动化辅修课程/信息/通信原理与应用 5.5 3-2.md
      - 数字电路与模拟电路: 辅修专业课程/自动化辅修课程/信息/数字电路与模拟电路 5.5 3-2.md
      - 电磁场与电磁波: 辅修专业课程/自动化辅修课程/信息/电磁场与电磁波 4 3-1.md
      - 信息论基础: 辅修专业课程/自动化辅修课程/信息/信息论基础 2.5 3-2.md
      
    - 自动化（电气）辅修课程:
      - 电力设备设计原理: 辅修专业课程/自动化辅修课程/电气/电力设备设计原理 2 3-2.md
      - 电气材料基础: 辅修专业课程/自动化辅修课程/电气/电气材料基础 2 3-2.md
      - 电力系统稳态分析: 辅修专业课程/自动化辅修课程/电气/电力系统稳态分析 4 3-2.md
      - 大数据科学与应用技术: 辅修专业课程/自动化辅修课程/电气/大数据科学与应用技术 2 3-2.md
      - 人工智能技术导论: 辅修专业课程/自动化辅修课程/电气/人工智能技术导论 2 3-2.md
      - 电力电子技术（英）: 辅修专业课程/自动化辅修课程/电气/电力电子技术（英） 3.5 3-2.md
      - 高电压技术: 辅修专业课程/自动化辅修课程/电气/高电压技术 3 3-2.md
    
    - 自动化（机械）辅修课程:
      - 机械制造技术基础: 辅修专业课程/自动化辅修课程/机械/机械制造技术基础 3 3-2.md
      - 材料成形技术基础: 辅修专业课程/自动化辅修课程/机械/材料成形技术基础 2 3-2.md
      - 机械设计基础: 辅修专业课程/自动化辅修课程/机械/机械设计基础 4 3-1.md
      - 工程材料基础: 辅修专业课程/自动化辅修课程/机械/工程材料基础 3 3-1.md

    - 电气（物联网）辅修课程:
      - 数据结构与算法I: 辅修专业课程/电气辅修课程/物联网/数据结构与算法I 3.5 2-1.md
      - 物联网原理: 辅修专业课程/电气辅修课程/物联网/物联网原理 3.5 2-2.md
      - 计算机网络原理: 辅修专业课程/电气辅修课程/物联网/计算机网络原理 3 3-1.md
      - 无线传感器网络: 辅修专业课程/电气辅修课程/物联网/无线传感器网络 2 3-2.md

    - 电气（材料）辅修课程:
      - 材料科学基础: 辅修专业课程/电气辅修课程/材料/材料科学基础 2.5 2-2.md
      - 材料化学: 辅修专业课程/电气辅修课程/材料/材料化学 2 3-1.md
      - 材料物理: 辅修专业课程/电气辅修课程/材料/材料物理 2 3-1.md
      - 材料研究方法: 辅修专业课程/电气辅修课程/材料/材料研究方法 2 3-2.md
      - 功能材料学: 辅修专业课程/电气辅修课程/材料/功能材料学 2 3-2.md
      - 材料制备与表征实验: 辅修专业课程/电气辅修课程/材料/材料制备与表征实验 1 4-1.md
    - 电气（能动）辅修课程:
      - 热工基础I: 辅修专业课程/电气辅修课程/能动/热工基础I 2.5 3-1.md
      - 现代电力生产技术: 辅修专业课程/电气辅修课程/能动/现代电力生产技术3 3-2.md
      - 储能原理与应用: 辅修专业课程/电气辅修课程/能动/储能原理与应用 3 3-2.md
      - 先进制冷低温技术: 辅修专业课程/电气辅修课程/能动/先进制冷低温技术 3 3-2.md
    - 能动（自动化）辅修课程:
      - 数字信号处理: 辅修专业课程/能动辅修课程/自动化/数字信号处理 3 3-1.md
      - 运筹学II: 辅修专业课程/能动辅修课程/自动化/运筹学II 2 3-2.md
      - 运动控制系统（钱）: 辅修专业课程/能动辅修课程/自动化/运动控制系统（钱） 2.5 3-2.md
      - 计算机原理与嵌入式系统设计（钱）: 辅修专业课程/能动辅修课程/自动化/计算机原理与嵌入式系统设计（钱） 4 3-1.md
      - 计算机网络原理与应用: 辅修专业课程/能动辅修课程/自动化/计算机网络原理与应用 2.5 3-2.md
    - 能动（材料）辅修课程:
      - 材料学: 辅修专业课程/能动辅修课程/材料/材料学 2 4-1.md
      - 材料工程基础: 辅修专业课程/能动辅修课程/材料/材料工程基础 2.5 3-2.md
      - 材料研究方法: 辅修专业课程/能动辅修课程/材料/材料研究方法 2 4-1.md
      - 材料性能: 辅修专业课程/能动辅修课程/材料/材料性能 2 4-1.md
      - 材料制备与表征实验: 辅修专业课程/能动辅修课程/材料/材料制备与表征实验 1 4-1.md
      - 材料科学基础: 辅修专业课程/能动辅修课程/材料/材料科学基础 2.5 3-2.md
    - 能动（飞行器）辅修课程:
      - 飞行动力学: 辅修专业课程/能动辅修课程/飞行器/飞行动力学 2 3-1.md
      - 航空发动机总体设计: 辅修专业课程/能动辅修课程/飞行器/航空发动机总体设计 2 4-1.md
      - 航空推进原理: 辅修专业课程/能动辅修课程/飞行器/航空推进原理 3 3-2.md
      - 航空飞行器总体设计: 辅修专业课程/能动辅修课程/飞行器/航空飞行器总体设计 2 3-2.md
      - 发动机综合实践: 辅修专业课程/能动辅修课程/飞行器/发动机综合实践 1 4-1.md
      - 航空发动机结构力学: 辅修专业课程/能动辅修课程/飞行器/航空发动机结构力学 2 3-2.md
    
    - 智造（计算机）辅修课程:
      - 数据结构与算法I: 辅修专业课程/智造辅修课程/计算机/数据结构与算法I 3.5 3-1.md
      - 计算机网络原理: 辅修专业课程/智造辅修课程/计算机/计算机网络原理 3 3-1.md
      - 数据库系统: 辅修专业课程/智造辅修课程/计算机/数据库系统 2.5 3-2.md
      - 算法分析与设计: 辅修专业课程/智造辅修课程/计算机/算法分析与设计 2.5 3-2.md
    - 智造（自动化）辅修课程:
      - 数字信号处理: 辅修专业课程/智造辅修课程/自动化/数字信号处理 3 3-1.md
      - 运筹学I: 辅修专业课程/智造辅修课程/自动化/运筹学I 3 3-2.md
      - 计算机原理与嵌入式系统设计（钱）: 辅修专业课程/智造辅修课程/自动化/计算机原理与嵌入式系统设计（钱） 4 3-1.md
      - 计算机网络原理与应用: 辅修专业课程/智造辅修课程/自动化/计算机网络原理与应用 2.5 3-2.md
    - 智造（力学）辅修课程:
      - 振动力学: 辅修专业课程/智造辅修课程/力学/振动力学 3 3-2.md
      - 计算固体力学: 辅修专业课程/智造辅修课程/力学/计算固体力学 2 3-2.md
      - 流体力学Ⅱ: 辅修专业课程/智造辅修课程/力学/流体力学Ⅱ 3 3-2.md
      - 弹性力学 I: 辅修专业课程/智造辅修课程/力学/弹性力学 I 4 3-1.md

extra:
  # 页脚可自定义内容（类似示例的存站说明、专业调整说明）
  footer:
  # 社交链接（若有需求，可配置 GitHub、公众号等）
  social:
    - icon: material/github
      #link:

copyright: Copyright © 钱院学辅

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

